#run:
#  skip-files:
#    - main.go
#    - app_test.go
#    - common.go

linters:

  disable-all: true
  enable:
    - asciicheck
#    - bidichk
    - bodyclose
#    - contextcheck
    - cyclop
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
#    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
#    - goconst
    - gocritic
    - gocyclo
    - goerr113
    - goheader
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
#    - ireturn
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
#    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
#    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
#    - tagliatelle
#    - tenv
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
#    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl

#linters-settings:
#  varnamelen:
#    ignore-decls:
#      - w http.ResponseWriter
#      - r *http.Request